version: "3.7"

services:
  db:
    image: postgres:12
    volumes:
      - app-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=insecure_password
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  app-db:
    external: true
