version: "3.7"

services:
  app:
    build:
      context: .
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=insecure_password
      - PGPORT=5432
    ports:
      - 80:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:12
    volumes:
      - app-db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=insecure_password
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  app-db:
    external: true
