version: "3.7"

services:
  app:
    build:
      context: .
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=insecure_password
      - PGPORT=5432
    ports:
      - 80:3000
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - app-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=insecure_password
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  app-db:
    external: true
